# Generated by Django 4.2 on 2024-05-07 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_rename_contactform_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='flan',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10, null=True),
        ),
    ]
