# Generated by Django 4.2 on 2024-05-10 00:01

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_flan_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None, verbose_name='Telefono de contacto'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='customer_email',
            field=models.EmailField(max_length=254, verbose_name='Correo electronico'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='customer_name',
            field=models.CharField(max_length=50, verbose_name='Nombre Completo'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='message',
            field=models.TextField(verbose_name='Mensaje'),
        ),
    ]
